/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as pagesRouteRouteImport } from './routes/(pages)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as pagesTentangKamiIndexRouteImport } from './routes/(pages)/tentang-kami/index'
import { Route as pagesPortofolioIndexRouteImport } from './routes/(pages)/portofolio/index'
import { Route as pagesLayananIndexRouteImport } from './routes/(pages)/layanan/index'
import { Route as pagesKaryaIndexRouteImport } from './routes/(pages)/karya/index'

const pagesRouteRoute = pagesRouteRouteImport.update({
  id: '/(pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesTentangKamiIndexRoute = pagesTentangKamiIndexRouteImport.update({
  id: '/tentang-kami/',
  path: '/tentang-kami/',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesPortofolioIndexRoute = pagesPortofolioIndexRouteImport.update({
  id: '/portofolio/',
  path: '/portofolio/',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesLayananIndexRoute = pagesLayananIndexRouteImport.update({
  id: '/layanan/',
  path: '/layanan/',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesKaryaIndexRoute = pagesKaryaIndexRouteImport.update({
  id: '/karya/',
  path: '/karya/',
  getParentRoute: () => pagesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/karya/': typeof pagesKaryaIndexRoute
  '/layanan/': typeof pagesLayananIndexRoute
  '/portofolio/': typeof pagesPortofolioIndexRoute
  '/tentang-kami/': typeof pagesTentangKamiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/karya': typeof pagesKaryaIndexRoute
  '/layanan': typeof pagesLayananIndexRoute
  '/portofolio': typeof pagesPortofolioIndexRoute
  '/tentang-kami': typeof pagesTentangKamiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(pages)': typeof pagesRouteRouteWithChildren
  '/(pages)/karya/': typeof pagesKaryaIndexRoute
  '/(pages)/layanan/': typeof pagesLayananIndexRoute
  '/(pages)/portofolio/': typeof pagesPortofolioIndexRoute
  '/(pages)/tentang-kami/': typeof pagesTentangKamiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/karya/' | '/layanan/' | '/portofolio/' | '/tentang-kami/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/karya' | '/layanan' | '/portofolio' | '/tentang-kami'
  id:
    | '__root__'
    | '/'
    | '/(pages)'
    | '/(pages)/karya/'
    | '/(pages)/layanan/'
    | '/(pages)/portofolio/'
    | '/(pages)/tentang-kami/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  pagesRouteRoute: typeof pagesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(pages)': {
      id: '/(pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof pagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/tentang-kami/': {
      id: '/(pages)/tentang-kami/'
      path: '/tentang-kami'
      fullPath: '/tentang-kami/'
      preLoaderRoute: typeof pagesTentangKamiIndexRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/portofolio/': {
      id: '/(pages)/portofolio/'
      path: '/portofolio'
      fullPath: '/portofolio/'
      preLoaderRoute: typeof pagesPortofolioIndexRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/layanan/': {
      id: '/(pages)/layanan/'
      path: '/layanan'
      fullPath: '/layanan/'
      preLoaderRoute: typeof pagesLayananIndexRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/karya/': {
      id: '/(pages)/karya/'
      path: '/karya'
      fullPath: '/karya/'
      preLoaderRoute: typeof pagesKaryaIndexRouteImport
      parentRoute: typeof pagesRouteRoute
    }
  }
}

interface pagesRouteRouteChildren {
  pagesKaryaIndexRoute: typeof pagesKaryaIndexRoute
  pagesLayananIndexRoute: typeof pagesLayananIndexRoute
  pagesPortofolioIndexRoute: typeof pagesPortofolioIndexRoute
  pagesTentangKamiIndexRoute: typeof pagesTentangKamiIndexRoute
}

const pagesRouteRouteChildren: pagesRouteRouteChildren = {
  pagesKaryaIndexRoute: pagesKaryaIndexRoute,
  pagesLayananIndexRoute: pagesLayananIndexRoute,
  pagesPortofolioIndexRoute: pagesPortofolioIndexRoute,
  pagesTentangKamiIndexRoute: pagesTentangKamiIndexRoute,
}

const pagesRouteRouteWithChildren = pagesRouteRoute._addFileChildren(
  pagesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  pagesRouteRoute: pagesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
