/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as pagesRouteRouteImport } from './routes/(pages)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as pagesTentangIndexRouteImport } from './routes/(pages)/tentang/index'

const pagesRouteRoute = pagesRouteRouteImport.update({
  id: '/(pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesTentangIndexRoute = pagesTentangIndexRouteImport.update({
  id: '/tentang/',
  path: '/tentang/',
  getParentRoute: () => pagesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tentang/': typeof pagesTentangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tentang': typeof pagesTentangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(pages)': typeof pagesRouteRouteWithChildren
  '/(pages)/tentang/': typeof pagesTentangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tentang/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tentang'
  id: '__root__' | '/' | '/(pages)' | '/(pages)/tentang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  pagesRouteRoute: typeof pagesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(pages)': {
      id: '/(pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof pagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/tentang/': {
      id: '/(pages)/tentang/'
      path: '/tentang'
      fullPath: '/tentang/'
      preLoaderRoute: typeof pagesTentangIndexRouteImport
      parentRoute: typeof pagesRouteRoute
    }
  }
}

interface pagesRouteRouteChildren {
  pagesTentangIndexRoute: typeof pagesTentangIndexRoute
}

const pagesRouteRouteChildren: pagesRouteRouteChildren = {
  pagesTentangIndexRoute: pagesTentangIndexRoute,
}

const pagesRouteRouteWithChildren = pagesRouteRoute._addFileChildren(
  pagesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  pagesRouteRoute: pagesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
